apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: blockchain
    app.kubernetes.io/instance: blockchain-join
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: blockchain-join
    meta.helm.sh/release-namespace: default
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: blockchain-join
      role: join
  template:
    metadata:
      labels:
        app: blockchain-join
        role: join
    spec:
      containers:
        - name: blockchain
          image: blockchain:latest
          args: ["miner", "join", "{{ .Values.host_url }}", "127.0.0.1:8080"]
          imagePullPolicy: Never
          env:
            - name: POSTGRES_USERNAME
              value: {{ .Values.db.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.password | quote }}
            - name: POSTGRES_HOST
              value: {{ .Values.db.host | quote }}