apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-open
  labels:
    app.kubernetes.io/name: blockchain
    app.kubernetes.io/instance: blockchain-open
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain
      role: open
  template:
    metadata:
      labels:
        app: blockchain
        role: open
    spec:
      containers:
        - name: blockchain
          image: blockchain:latest
          args: ["full", "open", "0.0.0.0:8080", "blockchain-open:8080"]
          imagePullPolicy: Never
          env:
            - name: POSTGRES_USERNAME
              value: {{ .Values.db.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.password | quote }}
            - name: POSTGRES_HOST
              value: {{ .Values.db.host | quote }}